language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
branches:
  only:
    - master
script:
  - xcodebuild -project KeyboardHelper.xcodeproj -scheme KeyboardHelper -sdk iphonesimulator build test | xcpretty && exit ${PIPESTATUS[0]}
after_success:
  - bash <(curl -s https://codecov.io/bash)

